#include <pgmspace.h>

#define SECRET
#define THINGNAME "CatFeederThingESP32"

const char WIFI_SSID[] = "YourWifiName";
const char WIFI_PASSWORD[] = "YourWifiPasword";
const char AWS_IOT_ENDPOINT[] = "your-iot-endpoint-ats.iot.us-west-2.amazonaws.com";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBb666
YOUR_AWS_CA_CERT
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUKwLRnOp5+DrT3R1N+wcKAaPRqQ0wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMTEyODA1NDk0
YOUR_CRT_CERT
zhSYqUeZnzR9m+2PdVk1b1B+CG0gVgsWRZTnWkJde+72Y09TYUdb05jcjhtKxX5X
if/ap52s9Wo0DFctkZF2uCBXxE0EcIAe5KQqcBm9BrdtqP3apXMZyVaD3BF4ok56
7m6iwRTAK3UFv7kg5bVO0Jd/hUElZS0TRzaFNM+WjfNIRkY6D5kCyuij0keIAl01
XxIuxXvM43wrb/6Zv1E7qUtlapIRWK/54uQZND1kVT2JKPjTq3cswa/Ls3Ab
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAvBYj4FjvVg2u/Bsm97ko0r5s9N7pfAuigaELzRHIRA5+ucDn
XNYz3IgehC4PwFBOkFonPL2XoIez3fXwBo4DVUvcjGFBnNaWF301FWBRN7rC3kJ2
e+0VXpqbfjPSp8Bp7jiLGkxBAJ5YYoX5xvJ2KQIDAQABAoIBAQCLoiw0TBIy4qm8
YOUR_PRIVATE_KEY
qwUMb9ku28+eq9ZEVrYuMiBjiFXRXaXNCD0IpoOAqT/YUKnmt3NlkOhtvaqm+P5G
FbCZ367KOWl+3mQ3tjAo2x7nrJhccPmS4/VROkuHbdUAcgq671Fm5j6Jk1bqeZm7
bnTD8T+FEHWW6sqx6KRpdD1tlVjYEHmcvei6E8qeqzzA+cgdu17HB6A=
-----END RSA PRIVATE KEY-----
)KEY";
